// This file allows Poedit to translate the category 
// (The free version of Poedit cannot parse yml files)
const _ = () => {};
window.categories = [
  _('restaurant'),
  _('hotel'),
  _('supermarket'),
  _('bar'),
  _('pharmacy'),
  _('leisure'),
  _('administration'),
  _('health'),
  _('education'),
  _('bank'),
  _('museum'),
  _('sport'),
  _('service'),
  _('french restaurant'),
  _('pizzeria'),
  _('burgers'),
  _('italian restaurant'),
  _('kebab restaurant'),
  _('sandwich'),
  _('asian restaurant'),
  _('japanese restaurant'),
  _('chinese restaurant'),
  _('creperie'),
  _('indian restaurant'),
  _('thai restaurant'),
  _('lebanese restaurant'),
  _('parking lot'),
  _('pitch'),
  _('place of worship'),
  _('recycling'),
  _('bicycle parking'),
  _('school'),
  _('park'),
  _('bakery'),
  _('clothes shop'),
  _('toilets'),
  _('sports centre'),
  _('hairdresser'),
  _('supermarket'),
  _('fast food'),
  _('historical place'),
  _('post office'),
  _('fuel station'),
  _('community centre'),
  _('convenience store'),
  _('car shop'),
  _('kindergarten or preschool'),
  _('camp site'),
  _('train station'),
  _('butcher'),
  _('tourist attraction'),
  _('hospital'),
  _('doctors office'),
  _('dentist'),
  _('physiotherapist'),
  _('pharmacy'),
  _('psychotherapist'),
  _('health'),
  _('library'),
  _('police'),
  _('optician'),
  _('graveyard'),
  _('beauty salon'),
  _('florist'),
  _('fire station'),
  _('shoes shop'),
  _('DIY store'),
  _('bicycle rental'),
  _('jewelry shop'),
  _('newsagent'),
  _('swimming pool'),
  _('furniture shop'),
  _('bookshop'),
  _('laundry'),
  _('sports shop'),
  _('theatre'),
  _('veterinarian'),
  _('greengrocer'),
  _('garden centre'),
  _('arts centre'),
  _('electronics shop'),
  _('cinema'),
  _('university'),
  _('travel agency'),
  _('sport'),
  _('post box'),
  _('playground'),
  _('marketplace'),
  _('confectionery'),
  _('locksmith'),
  _('shoemaker'),
  _('liquor store'),
  _('Delicatessen'),
  _('greengrocer'),
  _('frozen food shop'),
  _('ice-cream shop'),
  _('fishmonger'),
  _('baby goods shop'),
  _('tattoo artist'),
  _('sex shop'),
  _('watches shop'),
  _('discount shop'),
  _('well being shop'),
  _('DIY clothes shop'),
  _('medical supply shop'),
  _('furnitures shop'),
  _('outdoor activities shop'),
  _('vehicules shop'),
  _('boat shop'),
  _('hobbies shop'),
  _('souvenir shop'),
  _('e-cigarette shop'),
  _('dry cleaner'),
  _('retirement home'),
  _('ticketing'),
  _('coworking'),
  _('pitch'),
  _('football_pitch'),
  _('boules_pitch'),
  _('basketball_pitch'),
  _('rugby_pitch'),
  _('tennis_pitch'),
  _('skateboard_pitch'),
  _('table_tennis_pitch'),
  _('equestrian_pitch'),
  _('running_track'),
  _('sports_hall'),
  _('sport_climbing'),
  _('sport_martial_art'),
  _('sport_badminton'),
  _('sport_baseball'),
  _('sport_beach_volley_ball'),
  _('sport_golf'),
  _('sport_handball'),
  _('sport_ice_skating'),
  _('sport_karting'),
  _('sport_motor'),
  _('sport_skiing'),
  _('sport_volleyball'),
  _('sport_sailing'),
  _('stadium'),
  _('viewpoint'),
];
