---
- label: _('restaurant')
  name: restaurant
  color: '#e06000'
  bgColor: '#ffe8d6'
  icon: restaurant
- label: _('hotel')
  name: hotel
  color: '#676e79'
  bgColor: '#e9eaec'
  icon: lodging
- label: _('organic_store')
  color: '#297a52'
  bgColor: '#e0f5eb'
  icon: greengrocer
  ecoResponsible: true
- label: _('second_hand')
  color: '#297a52'
  bgColor: '#e0f5eb'
  icon: second-hand
  ecoResponsible: true
- label: _('zero_waste')
  color: '#297a52'
  bgColor: '#e0f5eb'
  icon: deli
  ecoResponsible: true
- label: _('supermarket')
  name: supermarket
  color: '#9500e0'
  bgColor: '#f1d6ff'
  icon: grocery
- label: _('ecotable')
  color: '#297a52'
  bgColor: '#e0f5eb'
  icon: restaurant
  ecoResponsible: true
- label: _('bar')
  name: bar
  color: '#e06000'
  bgColor: '#ffe8d6'
  icon: bar
- label: _('pharmacy')
  name: pharmacy
  color: '#0051e0'
  bgColor: '#d6e5ff'
  icon: pharmacy
- label: _('leisure')
  name: leisure
  color: '#e00004'
  bgColor: '#ffd6d7'
  icon: cinema
- label: _('administration')
  name: administrative
  color: '#676e79'
  bgColor: '#e9eaec'
  icon: town-hall
- label: _('health')
  name: health
  color: '#0051e0'
  bgColor: '#d6e5ff'
  icon: hospital
- label: _('education')
  name: education
  color: '#676e79'
  bgColor: '#e9eaec'
  icon: school
- label: _('bank')
  name: bank
  color: '#676e79'
  bgColor: '#e9eaec'
  icon: bank
- label: _('museum')
  name: museum
  color: '#e00004'
  bgColor: '#ffd6d7'
  icon: museum
- label: _('sport')
  name: fitness
  color: '#676e79'
  bgColor: '#e9eaec'
  icon: basketball

# Only categories with 'icon' are visible as action buttons.
# Below are the categories that are only accessible
# via queries (with detected intention) or URL
- label: _('service')
  name: service
  color: '#a125be'
- label: _('french restaurant')
  name: food_french
- label: _('pizzeria')
  name: food_pizza
- label: _('burgers')
  name: food_burger
- label: _('italian restaurant')
  name: food_italian
- label: _('kebab restaurant')
  name: food_kebab
- label: _('sandwich')
  name: food_sandwich
- label: _('asian restaurant')
  name: food_asian
- label: _('japanese restaurant')
  name: food_japanese
- label: _('chinese restaurant')
  name: food_chinese
- label: _('creperie')
  name: food_crepe
- label: _('indian restaurant')
  name: food_indian
- label: _('thai restaurant')
  name: food_thai
- label: _('vietnamese restaurant')
  name: food_vietnamese
- label: _('lebanese restaurant')
  name: food_lebanese
- label: _('parking lot')
  name: parking
- label: _('pitch')
  name: pitch
- label: _('place of worship')
  name: place_of_worship
- label: _('recycling')
  name: recycling
- label: _('bicycle parking')
  name: bicycle_parking
- label: _('school')
  name: school
- label: _('park')
  name: park
- label: _('bakery')
  name: shop_bakery
- label: _('clothes shop')
  name: shop_clothes
- label: _('toilets')
  name: toilets
- label: _('sports centre')
  name: sports_centre
- label: _('hairdresser')
  name: shop_hairdresser
- label: _('supermarket')
  name: shop_supermarket
- label: _('fast food')
  name: fast_food
- label: _('historical place')
  name: historic
- label: _('post office')
  name: post_office
- label: _('fuel station')
  name: fuel
- label: _('community centre')
  name: community_centre
- label: _('convenience store')
  name: shop_convenience
- label: _('car shop')
  name: shop_car
- label: _('kindergarten or preschool')
  name: kindergarten
- label: _('camp site')
  name: camp_site
- label: _('train station')
  name: station
- label: _('butcher')
  name: shop_butcher
- label: _('tourist attraction')
  name: attraction
- label: _('hospital')
  name: health_hospital
- label: _('doctors office')
  name: health_doctors
- label: _('dentist')
  name: health_dentist
- label: _('physiotherapist')
  name: health_physiotherapist
- label: _('pharmacy')
  name: health_pharmacy
- label: _('psychotherapist')
  name: health_psychotherapist
- label: _('health')
  name: health_other
- label: _('library')
  name: library
- label: _('police')
  name: police
- label: _('optician')
  name: shop_optician
- label: _('graveyard')
  name: grave_yard
- label: _('florist')
  name: shop_florist
- label: _('fire station')
  name: fire_station
- label: _('shoes shop')
  name: shop_shoes
- label: _('DIY store')
  name: shop_doityourself
- label: _('bicycle rental')
  name: bicycle_rental
- label: _('jewelry shop')
  name: shop_jewelry
- label: _('newsagent')
  name: shop_newsagent
- label: _('swimming pool')
  name: swimming
- label: _('furniture shop')
  name: shop_furniture
- label: _('bookshop')
  name: shop_books
- label: _('laundry')
  name: shop_laundry
- label: _('sports shop')
  name: shop_sports
- label: _('theatre')
  name: theatre
- label: _('veterinarian')
  name: veterinary
- label: _('greengrocer')
  name: shop_greengrocer
- label: _('garden centre')
  name: shop_garden_centre
- label: _('arts centre')
  name: arts_centre
- label: _('electronics shop')
  name: shop_electronics
- label: _('cinema')
  name: cinema
- label: _('university')
  name: university
- label: _('travel agency')
  name: shop_travel_agency
- label: _('post box')
  name: post_box
- label: _('playground')
  name: playground
- label: _('marketplace')
  name: marketplace
- label: _('confectionery')
  name: shop_confectionery
- label: _('locksmith')
  name: shop_locksmith
- label: _('shoemaker')
  name: craft_shoemaker
- label: _('liquor store')
  name: shop_alcohol
- label: _('Delicatessen')
  name: shop_fine_food
- label: _('greengrocer')
  name: shop_crop
- label: _('frozen food shop')
  name: shop_frozen_food
- label: _('ice-cream shop')
  name: amenity_ice_cream
- label: _('fishmonger')
  name: shop_seafood
- label: _('baby goods shop')
  name: shop_baby_goods
- label: _('tattoo artist')
  name: shop_tatoo
- label: _('sex shop')
  name: shop_erotic
- label: _('watches shop')
  name: shop_watches
- label: _('discount shop')
  name: shop_discount
- label: _('well being shop')
  name: shop_well_being
- label: _('DIY clothes shop')
  name: shop_doityourself_clothes
- label: _('medical supply shop')
  name: shop_medical_supply
- label: _('furnitures shop')
  name: shop_furnitures
- label: _('outdoor activities shop')
  name: shop_outdoor_activites
- label: _('vehicules shop')
  name: shop_vehicules
- label: _('boat shop')
  name: shop_boat
- label: _('hobbies shop')
  name: shop_hobbies
- label: _('souvenir shop')
  name: shop_gift
- label: _('e-cigarette shop')
  name: shop_e-cigarette
- label: _('dry cleaner')
  name: shop_dry_cleaning
- label: _('retirement home')
  name: retirement_home
- label: _('ticketing')
  name: shop_ticket
- label: _('coworking')
  name: coworking
- label: _('pitch')
  name: pitch
- label: _('soccer pitch')
  name: football_pitch
- label: _('boules pitch')
  name: boules_pitch
- label: _('basketball pitch')
  name: basketball_pitch
- label: _('rugby pitch')
  name: rugby_pitch
- label: _('tennis pitch')
  name: tennis_pitch
- label: _('skateboard pitch')
  name: skateboard_pitch
- label: _('table tennis pitch')
  name: table_tennis_pitch
- label: _('equestrian pitch')
  name: equestrian_pitch
- label: _('running track')
  name: running_track
- label: _('sports hall')
  name: sports_hall
- label: _('climbing')
  name: sport_climbing
- label: _('martial art')
  name: sport_martial_art
- label: _('badminton')
  name: sport_badminton
- label: _('baseball')
  name: sport_baseball
- label: _('beach-volley')
  name: sport_beach_volley_ball
- label: _('golf')
  name: sport_golf
- label: _('handball')
  name: sport_handball
- label: _('ice skating')
  name: sport_ice_skating
- label: _('karting')
  name: sport_karting
- label: _('car circuit')
  name: sport_motor
- label: _('skiing')
  name: sport_skiing
- label: _('volleyball')
  name: sport_volleyball
- label: _('sailing')
  name: sport_sailing
- label: _('stadium')
  name: stadium
- label: _('viewpoint')
  name: viewpoint
- label: _('charging station')
  name: charging_station
- label: _('airport')
  name: airport
- label: _('subway')
  name: subway
- label: _('bus stop')
  name: bus_stop
- label: _('bus station')
  name: bus_station
- label: _('tram stop')
  name: tram_stop
- label: _('public transport station')
  name: public_transport_station
- label: _('water place')
  name: place_water
- label: _('public bookcase')
  name: public_bookcase
- label: _('osteopathy')
  name: health_osteopathy
- label: _('healthcare laboratory')
  name: healthcare_laboratory
- label: _('shop funeral directors')
  name: shop_funeral_directors
- label: _('landuse military')
  name: landuse_military
- label: _('insurance')
  name: office_assurance
- label: _('lawyer')
  name: lawyer
