name: Erdapfel CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -yq libstdc++6 gettext

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build
      run: |
        npm install -g npm@8
        npm ci
        TEST=true npm run build -- --mode=production
    
    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test
