name: Erdapfel CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Install system dependencies
      # python3 dependencies needed to run transifex-client
      run: |
        sudo apt-get update 
        sudo apt-get install -yq libstdc++6 gettext
        sudo apt-get install -yq python3.5 python3-pip python3-setuptools

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"

    - name: Build
      run: |
        npm ci
        TEST=true npm run build -- --mode=production
    
    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Push translation keys to Transifex
      if: github.ref == 'refs/heads/master'
      run: bash .tx/push.sh
      env:
        TRANSIFEX_API_USER: api
        TRANSIFEX_API_KEY: ${{ secrets.TRANSIFEX_API_KEY }}
