on: push
name: packtracker.io
jobs:
  report:
    name: report webpack stats
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: report webpack stats
      uses: packtracker/report@2.2.7
      env:
        PT_PROJECT_TOKEN: ${{ secrets.packtracker_token }}
        WEBPACK_CONFIG_PATH: ./config/webpack/production.js
